version: 2
jobs:
  build:
    docker:
      - image: python:2.7
    working_directory: /gordon-test
    resource_class: small
    steps:
      - checkout
      - run:
          command: echo HI

workflows:
  version: 2
  pipeline:
    jobs:
      - hold:
          type: approval
      - build:
          require:
            - hold

