version: 2
jobs:
  build:
    docker:
      - image: python:2.7
    working_directory: /gordon-test
    resource_class: small
    steps:
      - checkout
      - run:
          command: echo ${CONTEXT_ENV_VAR}

workflows:
  version: 2
  every-minute:
    triggers:
      - schedule:
          cron: '* * * * *'
          filters:
            branches:
              only:
                - master
    jobs:
      - build
  pipeline:
    jobs:
      - hold:
          type: approval
      - build:
          context: org-global
          requires:
            - hold

