version: 2
jobs:
  build:
    docker:
      - image: python:2.7
    working_directory: /gordon-test
    resource_class: small
    steps:
      - checkout

      - run:
          command: echo ${CONTEXT_VARIABLE}
          name: Print custom context variable
workflows:
  version: 2
  pipeline:
    jobs:
      - build:
          context: custom-name

