version: 2
jobs:
  build:
    docker:
      - image: python:2.7
    working_directory: /gordon-test
    resource_class: small
    steps:
      - checkout
      - run:
          command: echo ${CONTEXT_ENV_VAR}
  test:
    docker:
      - image: python:2.7
    working_directory: /gordon-test
    resource_class: small
    steps:
      - checkout
      - run:
          command: sleep 10 && echo testing

  deploy:
    docker:
      - image: python:2.7
    working_directory: /gordon-test
    resource_class: small
    steps:
      - checkout
      - run:
          command: sleep 10 && echo deploying

workflows:
  version: 2
  pipeline:
    jobs:
      - test
