version: 2
jobs:
  build:
    docker:
      - image: python:2.7
    working_directory: /gordon-test
    resource_class: small
    steps:
      - run:
          command: sleep 20

workflows:
  version: 2
  pipeline:
    jobs:
      - build

  scheduled:
    triggers:
      - schedule:
          cron: '* * * * *'
          filters:
            branches:
              only:
                - master
    jobs:
      - build

